### ISSUE TITLE
Add coverage / minimum coverage

### ISSUE THREAD

**Issue by ZaxR** [ZaxR/bulwark#44]
E.g. something like:

# .codecov.yaml
```
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch: off
```

# .coveragerc   
```
[run]
omit = *tests*
```
